import Shining
 
##Modded Version
# Implemented Delim for C++
# delimiter : #
 
EffectTable = {

    15550 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15551 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15552 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15553 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15554 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15555 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15556 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15557 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15558 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15559 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],	
    15570 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15571 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15572 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15573 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15574 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15575 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15576 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15577 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15578 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15579 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15590 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15591 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15592 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15593 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15594 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15595 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15596 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15597 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15598 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15599 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15610 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15611 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15612 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15613 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15614 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15615 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15616 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15617 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15618 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
    15619 : ["d:/ymir work/pc/common/effect/armor/demoniaca_red.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15660 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15661 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15662 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15663 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15664 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15665 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15666 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15667 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15668 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15669 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15670 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15671 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15672 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15673 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15674 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15675 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15676 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15677 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15678 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15679 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15680 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15681 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15682 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15683 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15684 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15685 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15686 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15687 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15688 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15689 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15690 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15691 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15692 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15693 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15694 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15695 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15695 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15697 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15698 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	15699 : ["d:/ymir work/pc/common/effect/armor/demoniaca_blue.mse#d:/ymir work/pc/common/effect/armor/akaya2_xmas.mse"],
	11130 : ["d:/ymir work/pc/common/effect/armor/armor_9.mse"],
    11131 : ["d:/ymir work/pc/common/effect/armor/armor_9.mse"],
	11132 : ["d:/ymir work/pc/common/effect/armor/armor_9.mse"],
    11133 : ["d:/ymir work/pc/common/effect/armor/armor_9.mse"]
}
 
 
def LoadEffectTable():
    for effect in EffectTable:
        for i in range(len(EffectTable[effect])):
            vnum = effect
            effectpath = EffectTable[effect][i]
        Shining.Add(vnum, effectpath)
