window = {
	"name" : "CreateCharacterWindow",
	"x" : 0, "y" : 0,
	"width" : SCREEN_WIDTH,	"height" : SCREEN_HEIGHT,
	"children" : (
		{
			"name" : "BackGround",
			"type" : "expanded_image",
			"x" : 0, "y" : 0,
			"x_scale" : float(SCREEN_WIDTH) / 1280.0,
			"y_scale" : float(SCREEN_HEIGHT) / 720.0,
			"image" : "tbx/createcharacterwindow/background.tga",
			"children" : (
				{
					"name" : "window_name",
					"type" : "image",
					"x" : 0, "y" : 35,
					"horizontal_align" : "center",
					"vertical_align" : "top",
					"image" : "tbx/createcharacterwindow/window.tga",
				},
				{
					"name" : "tbx",
					"type" : "image",
					"x" : 120, "y" : 20,
					"horizontal_align" : "right",
					"vertical_align" : "top",
					"image" : "tbx/createcharacterwindow/tbx.tga",
				},
				{
					"name" : "board",
					"type" : "image",
					"x" : SCREEN_WIDTH * (-550) / 1900,
					"y" : SCREEN_HEIGHT * (0) / 280,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"image" : "tbx/createcharacterwindow/board.tga",
					"children" : (
						{
							"name" : "char_name",
							"type" : "image", 
							"x" : 0, "y" : -255,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/char/sura_char.tga",
						},
						{
							"name" : "char_desc",
							"type" : "image", 
							"x" : 0, "y" : -190,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/desc/warrior_desc.tga",
						},
						{
							"name" : "char_image",
							"type" : "image", 
							"x" : 0, "y" : -80,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/image/warrior_image.tga",
						},
						{
							"name" : "name_slotbar",
							"type" : "image",
							"x" : 0, "y" : 30,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/slotbar.tga",
							"children" : (
								{
									"name" : "name",
									"type" : "editline",
									"x" : 12, "y" : 9,
									"width" : 200, "height" : 17,
									"color" : 0xffc8aa80,
									"input_limit": 16,
									"enable_codepage": 0,
								},
							),
						},
						{
							"name" : "gender_slotbar",
							"type" : "image",
							"x" : 0, "y" : 85,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/slotbar.tga",
							"children" : (
								{
									"name" : "gender",
									"type" : "text",
									"x" : 12, "y" : 9,
									"color" : 0xffc8aa80,
									"text" : "Ch³op",
								},
								{
									"name" : "gender_left",
									"type" : "radio_button",
									"x" : 85, "y" : 0,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"default_image" : "tbx/createcharacterwindow/left_0.tga",
									"over_image" : "tbx/createcharacterwindow/left_1.tga",
									"down_image" : "tbx/createcharacterwindow/left_2.tga",
								},
								{
									"name" : "gender_right",
									"type" : "radio_button",
									"x" : 105, "y" : 0,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"default_image" : "tbx/createcharacterwindow/right_0.tga",
									"over_image" : "tbx/createcharacterwindow/right_1.tga",
									"down_image" : "tbx/createcharacterwindow/right_2.tga",
								},
							),
						},
						{
							"name" : "hair_slotbar",
							"type" : "image",
							"x" : 0, "y" : 138,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"image" : "tbx/createcharacterwindow/slotbar.tga",
							"children" : (
								{
									"name" : "hair",
									"type" : "text",
									"x" : 12, "y" : 9,
									"color" : 0xffc8aa80,
									"text" : "Ch³op",
								},
								{
									"name" : "hair_left",
									"type" : "button",
									"x" : 85, "y" : 0,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"default_image" : "tbx/createcharacterwindow/left_0.tga",
									"over_image" : "tbx/createcharacterwindow/left_1.tga",
									"down_image" : "tbx/createcharacterwindow/left_2.tga",
								},
								{
									"name" : "hair_right",
									"type" : "button",
									"x" : 105, "y" : 0,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"default_image" : "tbx/createcharacterwindow/right_0.tga",
									"over_image" : "tbx/createcharacterwindow/right_1.tga",
									"down_image" : "tbx/createcharacterwindow/right_2.tga",
								},
							),
						},
						{
							"name" : "create_button",
							"type" : "button",
							"x" : 0, "y" : 185,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "tbx/createcharacterwindow/create_0.tga",
							"over_image" : "tbx/createcharacterwindow/create_1.tga",
							"down_image" : "tbx/createcharacterwindow/create_2.tga",
						},
						{
							"name" : "cancel_button",
							"type" : "button",
							"x" : 0, "y" : 225,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "tbx/createcharacterwindow/cancel_0.tga",
							"over_image" : "tbx/createcharacterwindow/cancel_1.tga",
							"down_image" : "tbx/createcharacterwindow/cancel_2.tga",
						},
					),
				},
				{
					"name" : "char_select",
					"type" : "image",
					"x" : 250,
					"y" : 230,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"image" : "tbx/createcharacterwindow/select/warrior_select.tga",
				},
				{
					"name" : "left_button",
					"type" : "button",
					"x" : 40,	"y" : 130,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "d:/ymir work/ui/intro/select/dragon_left_button_01.sub",
					"over_image" : "d:/ymir work/ui/intro/select/dragon_left_button_02.sub",
					"down_image" : "d:/ymir work/ui/intro/select/dragon_left_button_03.sub",
				},
				{
					"name" : "right_button",
					"type" : "button",
					"x" : 510,	"y" : 130,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "d:/ymir work/ui/intro/select/dragon_right_button_01.sub",
					"over_image" : "d:/ymir work/ui/intro/select/dragon_right_button_02.sub",
					"down_image" : "d:/ymir work/ui/intro/select/dragon_right_button_03.sub",
				},
			),
		},
	),
}
