window = {
	"name" : "selectcharacterwindow",
	"x" : 0, "y" : 0,
	"width" : SCREEN_WIDTH,	"height" : SCREEN_HEIGHT,
	"children" : (
		{
			"name" : "BackGround",
			"type" : "expanded_image",
			"x" : 0, "y" : 0,
			"x_scale" : float(SCREEN_WIDTH) / 1920.0,
			"y_scale" : float(SCREEN_HEIGHT) / 1080.0,
			"image" : "yamato_select/bg.jpg",
			"children" : (
				{
					"name" : "window_name",
					"type" : "image",
					"x" : 0, "y" : 35,
					"horizontal_align" : "center",
					"vertical_align" : "top",
					"image" : "tbx/selectcharacterwindow/window.tga",
				},
				{
					"name" : "tbx",
					"type" : "image",
					"x" : 120, "y" : 20,
					"horizontal_align" : "right",
					"vertical_align" : "top",
					"image" : "tbx/selectcharacterwindow/tbx.tga",
				},
				{
					"name" : "board",
					"type" : "image",
					"x" : SCREEN_WIDTH * (-550) / 1900,
					"y" : SCREEN_HEIGHT * (0) / 280,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"image" : "tbx/selectcharacterwindow/board.tga",
					"children" : (
						{
							"name" : "empire_image",
							"type" : "image",
							"x" : 0, "y" : -220,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"image" : "tbx/selectcharacterwindow/flag_jinno.tga",
						},
						{
							"name" : "name_slotbar",
							"type" : "slotbar",
							"x" : 50, "y" : -137,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 110, "height" : 17,
							"children" : (
								{
									"name" : "name",
									"type" : "text",
									"x" : 0, "y" : 0,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "empire_slotbar",
							"type" : "slotbar",
							"x" : 50, "y" : -111,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 110, "height" : 17,
							"children" : (
								{
									"name" : "empire",
									"type" : "text",
									"x" : 0, "y" : 0,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "level_slotbar",
							"type" : "slotbar",
							"x" : 50, "y" : -111+28,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 110, "height" : 17,
							"children" : (
								{
									"name" : "level",
									"type" : "text",
									"x" : 0, "y" : 0,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "playtime_slotbar",
							"type" : "slotbar",
							"x" : 50, "y" : -111+56,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 110, "height" : 17,
							"children" : (
								{
									"name" : "playtime",
									"type" : "text",
									"x" : 0, "y" : 0,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "guild_slotbar",
							"type" : "slotbar",
							"x" : 50, "y" : -111+83,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 110, "height" : 17,
							"children" : (
								{
									"name" : "guild",
									"type" : "text",
									"x" : 0, "y" : 0,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "gauge_hth",
							"type" : "gauge",
							"x" : 30, "y" : 24,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 100,
							"color" : "red",
							"children" : (
								{
									"name" : "hth_slotbar",
									"type" : "slotbar",
									"x" : 120, "y" : -6,
									"width" : 30, "height" : 17,
									"children" : (
										{
											"name" : "hth",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
							),
						},
						{
							"name" : "gauge_int",
							"type" : "gauge",
							"x" : 30, "y" : 49,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 100,
							"color" : "pink",
							"children" : (
								{
									"name" : "int_slotbar",
									"type" : "slotbar",
									"x" : 120, "y" : -6,
									"width" : 30, "height" : 17,
									"children" : (
										{
											"name" : "int",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
							),
						},
						{
							"name" : "gauge_str",
							"type" : "gauge",
							"x" : 30, "y" : 75,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 100,
							"color" : "purple",
							"children" : (
								{
									"name" : "str_slotbar",
									"type" : "slotbar",
									"x" : 120, "y" : -6,
									"width" : 30, "height" : 17,
									"children" : (
										{
											"name" : "str",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
							),
						},
						{
							"name" : "gauge_dex",
							"type" : "gauge",
							"x" : 30, "y" : 103,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"width" : 100,
							"color" : "blue",
							"children" : (
								{
									"name" : "dex_slotbar",
									"type" : "slotbar",
									"x" : 120, "y" : -6,
									"width" : 30, "height" : 17,
									"children" : (
										{
											"name" : "dex",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
							),
						},
						{
							"name" : "select_button",
							"type" : "button",
							"x" : 0, "y" : 160,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "tbx/selectcharacterwindow/select_0.tga",
							"over_image" : "tbx/selectcharacterwindow/select_1.tga",
							"down_image" : "tbx/selectcharacterwindow/select_2.tga",
						},
						{
							"name" : "create_button",
							"type" : "button",
							"x" : -75, "y" : 205,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "tbx/selectcharacterwindow/create_0.tga",
							"over_image" : "tbx/selectcharacterwindow/create_1.tga",
							"down_image" : "tbx/selectcharacterwindow/create_2.tga",
						},
						{
							"name" : "delete_button",
							"type" : "button",
							"x" : 75, "y" : 205,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "tbx/selectcharacterwindow/delete_0.tga",
							"over_image" : "tbx/selectcharacterwindow/delete_1.tga",
							"down_image" : "tbx/selectcharacterwindow/delete_2.tga",
						},
					),
				},
				{
					"name" : "left_button",
					"type" : "button",
					"x" : 40,	"y" : 140,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "d:/ymir work/ui/intro/select/dragon_left_button_01.sub",
					"over_image" : "d:/ymir work/ui/intro/select/dragon_left_button_02.sub",
					"down_image" : "d:/ymir work/ui/intro/select/dragon_left_button_03.sub",
				},
				{
					"name" : "right_button",
					"type" : "button",
					"x" : 310,	"y" : 140,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "d:/ymir work/ui/intro/select/dragon_right_button_01.sub",
					"over_image" : "d:/ymir work/ui/intro/select/dragon_right_button_02.sub",
					"down_image" : "d:/ymir work/ui/intro/select/dragon_right_button_03.sub",
				},
			),
		},
	),
}
